"""Slide-to-image conversion: PPTX → PDF (LibreOffice) → PNG (PyMuPDF)."""
import subprocess
from pathlib import Path

from checker.config import LIBREOFFICE_PATH, SLIDE_ZOOM


def convert_pptx_to_images(pptx_path: Path, output_dir: Path) -> dict[int, Path]:
    """
    Convert PPTX to per-slide PNG images.
    Returns dict: slide_number → Path to PNG.
    Uses cache: if images exist and are newer than PPTX, skip.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # Check cache
    existing = sorted(output_dir.glob("slide_*.png"))
    if existing:
        pptx_mtime = pptx_path.stat().st_mtime
        oldest_img = min(p.stat().st_mtime for p in existing)
        if oldest_img >= pptx_mtime:
            return _collect_images(existing)
        # PPTX is newer — regenerate
        for old in existing:
            old.unlink()
        for old_pdf in output_dir.glob("*.pdf"):
            old_pdf.unlink()

    # Step 1: PPTX → PDF via LibreOffice
    pdf_path = output_dir / f"{pptx_path.stem}.pdf"
    if not pdf_path.exists():
        try:
            subprocess.run(
                [LIBREOFFICE_PATH, "--headless", "--convert-to", "pdf",
                 "--outdir", str(output_dir), str(pptx_path)],
                check=True, capture_output=True, timeout=120,
            )
        except (FileNotFoundError, subprocess.CalledProcessError) as e:
            print(f"    WARN: LibreOffice conversion failed: {e}")
            return {}

    if not pdf_path.exists():
        print("    WARN: PDF not generated by LibreOffice")
        return {}

    # Step 2: PDF → PNG via PyMuPDF
    try:
        import fitz
    except ImportError:
        print("    WARN: PyMuPDF not installed: pip install PyMuPDF")
        return {}

    doc = fitz.open(str(pdf_path))
    slide_images: dict[int, Path] = {}
    mat = fitz.Matrix(SLIDE_ZOOM, SLIDE_ZOOM)

    for page_num in range(len(doc)):
        img_path = output_dir / f"slide_{page_num + 1:03d}.png"
        if not img_path.exists():
            pix = doc[page_num].get_pixmap(matrix=mat)
            pix.save(str(img_path))
        slide_images[page_num + 1] = img_path

    doc.close()
    return slide_images


def _collect_images(paths: list[Path]) -> dict[int, Path]:
    """Parse slide_NNN.png filenames into {number: path} dict."""
    result: dict[int, Path] = {}
    for p in paths:
        try:
            idx = int(p.stem.split("_")[1])
            result[idx] = p
        except (ValueError, IndexError):
            pass
    return result
